.github/workflows/lint.yaml
README.md
configs/sample.config.toml
datastore/postgres.go
db/postgres/schema.go
engine/worker.go
examples/aws_create_master.yaml
examples/aws_split_and_stitch.yaml
examples/hls.yaml
examples/resize_image.yaml
examples/split_and_stitch.yaml
input/task.go
input/validate.go
input/validate_test.go
internal/coordinator/coordinator.go
internal/coordinator/coordinator_test.go
internal/worker/worker.go
internal/worker/worker_test.go
mq/inmemory_test.go
mq/rabbitmq_test.go
runtime/docker.go
runtime/docker_test.go
task.go

This PR adds support for local mounts. 
The implementation extends the existing ability to specify volumes. to share state between the task and its `pre` and `post` tasks. e.g.: 
```yaml
name: my task
image: some:image
volumes:
- /myvolume
``` 
To specify a local mount the job author will use the following syntax: 
```yaml
name: my task
image: some:image
volumes:
- /some/local/dir:/target/mount
``` 
Also, 
* `worker.mounts.enabled` must be set to `true` in the worker configs (it's `false` by default)
* the mount point **not** appearing in the `worker.mounts.denylist` patterns  
* the mount **is** appearing in the `worker.mounts.allowlist`

Added support for local mounts

---

docker-compose.yaml

After tork-web port changes this docker-compose file has to be fixed also
relates to this commit:
https://github.com/runabol/tork-web/commit/ebd37c9a74e28a91c49577d79ce1f48a0fb32ec8

fix tork-web internal port in docker-compose

---

cli/cli.go
conf/conf.go
configs/sample.config.toml
engine/worker.go
go.mod
input/validate.go
input/validate_test.go
internal/cache/cache.go
internal/cache/cache_test.go
internal/coordinator/coordinator_test.go
internal/reexec/command_linux.go
internal/reexec/command_unix.go
internal/reexec/command_unsupported.go
internal/reexec/command_windows.go
internal/reexec/reexec_test.go
internal/reexec/rexec.go
internal/runtime/docker/docker.go
internal/runtime/docker/docker_test.go
internal/runtime/shell/shell.go
internal/runtime/shell/shell_test.go
internal/worker/api_test.go
internal/worker/worker_test.go

This PR introduces a new `Runtime` implementation for executing tasks directly on the shell. 
In order to activate the new runtime in a given worker, a new config parameter -- `runtime.type` (set to `docker` by default) needs to be set to `shell`. 
The main caveat with this runtime environment is an almost complete lack of security. Job submissions have nothing stopping them from wreaking havoc to the host machine where the Tork Worker is running including killing the Tork process itself. Tasks are given the same privileges that the Tork process is given on startup. Therefore the use of this runtime implementation should be highly discouraged except for cases where Tork is used exclusively by trusted parties.

Added support for Shell runtime

---

conf/conf.go
conf/conf_test.go
configs/sample.config.toml
engine/broker.go
mq/rabbitmq.go
mq/rabbitmq_test.go
runtime/docker/docker_test.go

From the RabbitMQ docs:
> RabbitMQ enforces a timeout is enforced on consumer delivery acknowledgement. This is a protection mechanism that helps detect buggy (stuck) consumers that never acknowledge deliveries. Such consumers can affect node's on disk data compaction and potentially drive nodes out of disk space.
> If a consumer does not ack its delivery for more than the timeout value **(30 minutes by default)***, its channel will be closed with a `PRECONDITION_FAILED` channel exception.
For certain use case (see https://github.com/runabol/tork/issues/208) the default 30 minutes timeout is not enough. 
This PR introduces a new config property: `broker.rabbitmq.consumer.timeout` to allow Tork administrators to configure the consumer timeout. For example: `broker.rabbitmq.consumer.timeout …

Added the ability to configure the consumer timeout

---

conf/conf_test.go

Add failing test to demonstrate issue in #218

Add failing test for loading configs with overriding env values

---

docker-compose.yaml
runtime/docker/docker.go
runtime/docker/docker_test.go

Error message:
```
Error response from daemon: remove aa16c17221124040986e1f432f3ae74e: volume is in use - [80106858a623d44b43e5640d34289eb22a0c6eb3bedb6b223f22f84aa92b0c24]
```
The root cause was not tracking the container ID after it was created but rather after it was started. 
This led to not deleting the volumes and the container when the task exited if the container never actually started.

Fixed remove volume bug

---

configs/sample.config.toml
datastore/postgres.go
datastore/postgres_test.go
db/postgres/schema.go
engine/coordinator.go
engine/worker.go
internal/coordinator/coordinator.go
internal/coordinator/coordinator_test.go
internal/host/host.go
internal/host/host_test.go
internal/worker/worker.go
node.go

This PR:
1. Adds support for coordinator heartbeats so coordinators are listed in the `/nodes` endpoint.
2. Adds support for configurable node names.

Coordinator heartbeat and node name

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Fixes #233 
@runabol How do you want to handle `minor` and `major` tags? Release drafter will auto-generate the tag based on the labels of the PR's that have been merged.
```yaml
version-resolver:
major:
labels:
- 'major'
minor:
labels:
- 'minor'
- '❗ Breaking Change'
patch:
labels:
- '✏️ Feature'
- '📒 Documentation'
- '🐛 Bug'
- '🤖 Dependencies'
- '🧹 Updates'
- '🔒 Security'
```
In my initial draft, I have left both `major`  and `minor` as place holders. All the other labels will increment the `patch` release. Do you want to move some of those or add new ones to manage the `minor` releases?

Add support for release-drafter

---

configs/sample.config.toml
engine/coordinator.go

Adds support for key-based authorization:
e.g.
```
curl -H "Authorization: Bearer some-key" http://localhost:8000/jobs
```
* For valid key it let's the request through.
* For invalid key, it sends `401 - Unauthorized` response.
* For missing key, it sends `400 - Bad Request` response.
* Skips `/health` requests.
Middleware is enabled by using the `TORK_MIDDLEWARE_WEB_KEYAUTH_ENABLED=true` env var (or corresponding config property) and the `TORK_MIDDLEWARE_WEB_KEYAUTH_KEY=some-key` for the key. Tork will generate a random key and print it to the console if the key is not specified.

Feature: Key Auth

---

internal/coordinator/handlers/completed.go
internal/coordinator/handlers/completed_test.go
internal/coordinator/handlers/pending.go
internal/coordinator/handlers/pending_test.go
task.go

When a conditional task `if` expression evaluates to `false` the task state will be set to `SKIPPED` instead of `COMPLETED`.

Feature: skipped task state

---

internal/logging/forwarder.go
internal/logging/forwarder_test.go
runtime/docker/docker.go
runtime/shell/shell.go
version.go

This PR improves log shipping by buffering source log messages for upto one second before forwarding them to the Coordinator. The intention is to reduce the amount of messages being generated by the worker as well as reduce the number of log parts in the database.

Log shipping improvements

---

datastore/postgres/postgres.go
datastore/postgres/record.go
db/postgres/schema.go
input/job.go
input/task.go
internal/coordinator/scheduler/scheduler.go
internal/coordinator/scheduler/scheduler_test.go
job.go
mq/queues.go
mq/rabbitmq.go
mq/rabbitmq_test.go
task.go

Adds support for task priority when using RabbitMQ as a broker. 
This features builds on RabbitMQ support for priority queues: https://www.rabbitmq.com/docs/priority
This change does require re-creating the task queues (by simply deleting them and letting Tork re-create them).
There is also a DB schema change adding the priority field to the `tasks` table:
```
alter table tasks add priority int default 0
```
To use priority in your jobs set the `priority` property on the task (values 1-9). Higher values indicate higher priority. Example:
```yaml
- name: my first task
image: alpine:3.18.3
run: sleep 3
priority: 1
```
This task will execute as a priority over tasks with no `priority` defined.
You can also set the default priority for a task at the job level:
```yaml
name: my job
defaults: …
```

Feature: task priority (RabbitMQ)

---

configs/sample.config.toml
datastore/datastore.go
datastore/inmemory/inmemory.go
datastore/inmemory/inmemory_test.go
datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
engine/coordinator.go
engine/engine_test.go
go.mod
internal/coordinator/api/api.go
internal/coordinator/scheduler/scheduler.go
internal/hash/hash.go
internal/hash/hash_test.go
job.go
user.go

This PR adds support for user creation and user assignment when a job is created.
1. New `users` table to store username and passwords (hashed).
2. A new built-in `guest` user that can be assigned to jobs when login is not enforced.
3. New endpoint to create users: `POST /users`.
4. `createdBy` field added to each job.
To turn on login using basic auth use `middleware.web.basicauth=true` or `TORK_MIDDLEWARE_WEB_BASICAUTH_ENABLED=true`

Feature: user authentication

---

datastore/inmemory/inmemory.go
datastore/inmemory/inmemory_test.go
datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
input/job.go
internal/slices/slices.go
internal/slices/slirces_test.go
job.go

This PR adds the ability to assign `tags` to a job. Example:
```yaml
name: my job
tags:
- tag1
- tag2
tasks:
- name: my first task
run: echo -n hello world
image: alpine:3.18.3
```
These tags can later be used to filter jobs when calling the search jobs endpoint:
```
GET /jobs?q=tag:tag1
```
Will match any jobs that is assigned the `tag1` tag.
```
GET /jobs?q=tags:tag1,tag3
```
Will match any jobs that has **at least one** of the listed `tags`

Feature: job tags

---

datastore/datastore.go
datastore/inmemory/inmemory.go
datastore/inmemory/inmemory_test.go
datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
input/job.go
input/validate.go
input/validate_test.go
internal/coordinator/api/api.go
job.go
role.go

This PR adds support for roles and permissions. 
Example:
```yaml
name: my job
permissions:
- role: some-role # the role's slug
- user: someuser # the user's username
...
```
Permissions specify which user(s) or role(s) should have access to this particular job.
Jobs without `permissions` will be viewable to all as they are now.

Feature: roles & permissions

---

configs/sample.config.toml
engine/worker.go
runtime/docker/bind.go
runtime/docker/bind_test.go

This PR allows the operator to only allow certain directories to be used as `source` points for a Bind mount. 
1. The new config `mounts.bind.sources` or `TORK_MOUNTS_BIND_SOURCES` can now be used to specify a list of allowed paths.
2. When not specified, all sources are allowed for backward compatibility.

Feature: Bind mount allowed sources

---

datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
input/job.go
internal/coordinator/handlers/job.go
internal/coordinator/handlers/job_test.go
job.go

This PR adds support for the automatic deletion of `COMPLETED` jobs. 
Example:
```yaml
name: my job
autoDelete: 
after: 5m
tasks:
...
```
Indicates that this job is to be deleted after at least 5 minutes after it has transitioned to a `COMPLETED` state has elapsed.

Feature: auto-delete jobs

---

datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
engine/coordinator.go
input/job.go
internal/redact/redact.go
internal/redact/redact_test.go
job.go
middleware/job/redact_test.go
middleware/task/redact_test.go

This PR adds first-class support for job-level secrets. 
This augments the existing key-based, pattern-matching support for redacting sensitive values.
1. Add a `secrets` namespace to the Job's Context object.
2. Turn on the redact middlewares by default.
Example:
```yaml
name: my job
secrets:
password: "secret"
tasks:
- name: my first task
run: |
echo do some work
image: alpine:3.18.3
env:
SECRET: "{{secrets.password}}"
```

Feature: secrets

---

runtime/docker/docker.go
runtime/docker/docker_test.go

This PR:
1. Improves the sandbox image build script to be more flexible.
2. Installs the `useradd` utility on the image if it does not already exist.
3. Does not create the `tork` user if it already exists.

Fix: better sandbox build script

---

middleware/job/webhook.go
middleware/job/webhook_test.go
middleware/task/webhook.go
middleware/task/webhook_test.go

This PR adds support for evaluating webhook headers against the job's context.

Feature: evaluate headers on webhooks

---

datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
datastore/postgres/record.go
db/postgres/schema.go
engine/coordinator.go
examples/service.yaml
go.mod
input/task.go
internal/coordinator/api/api.go
internal/coordinator/api/api_test.go
internal/coordinator/handlers/started.go
internal/worker/api.go
internal/worker/api_test.go
internal/worker/worker.go
internal/worker/worker_test.go
node.go
runtime/docker/docker.go
task.go

This PR adds support for long-running or service tasks:
Potential use-cases:
1. Long-running tasks that retain their state over time. 
2. Running temporary APIs.
Example:
1. Create a job containing a task with a `ports` block.
```yaml
name: my service job
tasks:
- name: my service task
image: node:14
run: |
node server.js
ports: 
- port: 8080
files:
server.js: |
const http = require('http');
const hostname = '0.0.0.0';
const port = 8080;
const server = http.createServer((req, res) => {
res.statusCode = 200;
res.setHeader('Content-Type', 'text/plain');
res.end('Hello World\n');
});
server.listen(port, hostname, () => {
console.log(`Server running at http://${hostname}:${port}/`);
});
```
```bash
JOB_ID=$(curl -s -X POST \
--data-binary @examples/service.yaml \
-H "Content-type: text/yaml" …
```

Feature: Service Tasks

---

datastore/datastore.go
datastore/inmemory/inmemory.go
datastore/inmemory/inmemory_test.go
datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
input/task.go
internal/cache/cache.go
internal/cache/cache_test.go
internal/coordinator/handlers/completed.go
internal/coordinator/handlers/completed_test.go
internal/coordinator/scheduler/scheduler.go
internal/coordinator/scheduler/scheduler_test.go
internal/slices/slices.go
internal/slices/slirces_test.go
task.go
task_test.go

Adds support for concurrency control on `each` tasks. 
By default [each tasks](https://www.tork.run/tasks#each-task) publish their sub-tasks to work queues all at once.
For each tasks with a large `list` this could result in saturating the cluster with many small tasks -- potentially "starving" other jobs.
This PR adds concurrency control, such that the job author can control the maximum number of each tasks that can execute at any given moment, across the entire cluster. Example:
```yaml
name: my job
tasks:
- name: sample each task
each:
list: "{{ sequence(1,5) }}"
concurrency: 1
task:
name: output task item
run: |
sleep $ITEM
echo -n "slept $ITEM seconds" > $TORK_OUTPUT
image: ubuntu:mantic
env:
ITEM: "{{item.value}}"
```
In this example, only 1 `each` task will execute at any given …

Each concurrency control

---

internal/worker/api.go
internal/worker/api_test.go
internal/worker/worker.go
internal/worker/worker_test.go
runtime/docker/docker.go
runtime/docker/docker_test.go
task.go

This PR build on PR https://github.com/runabol/tork/pull/433 and adds support for user-defined host port on service tasks. 
Example:
```yaml
name: my service job
tasks:
- name: my service task
image: node:14
run: |
node server.js
ports: 
- port: 9090:8080 # host-port:container-port
files:
server.js: |
const http = require('http');
const hostname = '0.0.0.0';
const port = 8080;
const server = http.createServer((req, res) => {
res.statusCode = 200;
res.setHeader('Content-Type', 'text/plain');
res.end('Hello World\n');
});
server.listen(port, hostname, () => {
console.log(`Server running at http://${hostname}:${port}/`);
});
```

Feature: host port for service tasks

---

configs/sample.config.toml
engine/coordinator.go

Body limit middleware sets the maximum allowed size for a request body, if the size exceeds the configured limit (default is `64K`, it sends `413 - Request Entity Too Large` response. The body limit is determined based on both `Content-Length` request header and actual content read, which makes it super secure.
Limit can be specified as `4x`, where x is one of the multiple from K, M, G, T or P.
Example:
```
TORK_MIDDLEWARE_WEB_BODYLIMIT=1M
```

Feature: body limit middleware

---

configs/sample.config.toml
engine/worker.go
middleware/job/webhook_test.go
runtime/docker/docker.go
runtime/docker/docker_test.go

This PR adds the ability to configure a custom `busybox` image name when using [sandbox mode](https://www.tork.run/runtime#sandbox-mode-experimental).
Example:
```
TORK_RUNTIME_DOCKER_BUSYBOX_IMAGE=myprivateregistry.com/busybox:stable
```

Feature: make busybox image name configurable

---

configs/sample.config.toml
datastore/postgres/postgres.go
datastore/postgres/postgres_test.go
engine/datastore.go

This PR:
1. Adds support for automatic expiry and deletion of jobs from the datastore after a configurable amount of time (default is 1 year). 
2. Renames the `datastore.postgres.task.logs.interval` config to `datastore.retention.logs.duration`.

Feature: job retention duration

---

input/job.go
internal/coordinator/api/api.go
internal/coordinator/api/api_test.go

This PR introduces a new feature  that allows users to optionally `wait` on a job to terminate upon submission.
When used the `POST /jobs` endpoint will block until the job arrived at a terminal state (`COMPLETED`, `FAILED`, `CANCELLED`) or after the defined timeout.
Example:
```yaml
name: hello world
wait:
timeout: "5s" # required
output: "{{ tasks.hello }}"
tasks:
- var: hello
name: simple task
image: ubuntu:mantic
run: echo -n hello world > $TORK_OUTPUT
```

Feature: job wait

---

configs/sample.config.toml
engine/worker.go
runtime/docker/docker.go
runtime/docker/docker_test.go
runtime/podman/podman.go
runtime/podman/podman_test.go

This pull request introduces a new feature to Tork, enabling users to configure workers to execute container tasks in [privileged mode](https://docs.docker.com/engine/containers/run/#runtime-privilege-and-linux-capabilities). The feature is opt-in and can be enabled by setting the appropriate environment variable based on the runtime in use:
* For Docker: Set `TORK_RUNTIME_DOCKER_PRIVILEGED=true`
* For Podman: Set `TORK_RUNTIME_PODMAN_PRIVILEGED=true`
When enabled, the worker will run container tasks with elevated privileges, allowing access to additional system resources and capabilities as defined by the respective runtime. This is particularly useful for workflows requiring privileged operations, such as interacting with host devices or performing system-level tasks.

Feature: privileged execution

---

broker/rabbitmq.go
configs/sample.config.toml
engine/broker.go

This PR introduces optional support for using Quorum queues when RabbitMQ is configured as the broker in Tork. Quorum queues provide enhanced durability and high availability through Raft-based replication, making them suitable for production environments requiring stronger data safety guarantees compared to classic queues.
**Changes**
* Added a new environment variable `TORK_BROKER_RABBITMQ_QUEUE_TYPE`, which defaults to classic.
* When set to `quorum`, Tork will declare all relevant queues (e.g., task queues managed by the Broker) as Quorum queues instead of `classic` ones.
* No changes to the default behavior—`classic` queues remain the standard to ensure backward compatibility.
**Testing and Caveats**
Quorum queues do not map 1:1 with classic queues in terms of behavior, migration, or …

Feature: support rabbitmq quorum queues

---

broker/queues.go
broker/rabbitmq.go
internal/coordinator/coordinator.go
internal/coordinator/handlers/redelivered.go
internal/coordinator/handlers/redelivered_test.go
middleware/task/task.go
task.go

This PR adds support for tracking task redeliveries (due to worker disconnection) capped to a maximum of 5.
The goal is to protect worker nodes from "poison tasks" where tasks are repeatedly causing a node to crash, at which point the message gets requeued and the cycle starts again. 
The implementation includes:
1. Adding a new Coordinator-managed `redeliveries` queue to which all redelivered tasks are sent to.
2. Adding an ephemeral `redeliveries` field to the `Task` struct. 
3. A new `redelivery` Coordinator handler which increments the task's `redeliveries` field and either resubmits it to the original queue, or to the `errors` queue when `redeliveries` threshold is met.

Feature: max task redelivery
